### ISSUE TITLE
endpoint participation delete

### ISSUE THREAD

**Issue by thabils** [SELab-2/OSOC-4#350]
```postgres_1      | 2022-04-27 20:14:18.468 UTC [40] ERROR:  operator does not exist: integer = character varying at character 111
postgres_1      | 2022-04-27 20:14:18.468 UTC [40] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
postgres_1      | 2022-04-27 20:14:18.468 UTC [40] STATEMENT:  SELECT student.id, student.edition_year, student.decision, student.email_sent 
postgres_1      | 	FROM student 
postgres_1      | 	WHERE student.id = $1::varchar
osoc-backend_1  | INFO:     172.18.0.1:53500 - "DELETE /participations?project_id=1&student_id=10 HTTP/1.1" 500 Internal Server Error
osoc-backend_1  | ERROR:    Exception in ASGI application
osoc-backend_1  | Traceback (most recent call last):
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 418, in _prepare_and_execute
osoc-backend_1  |     prepared_stmt, attributes = await adapt_connection._prepare(
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 660, in _prepare
osoc-backend_1  |     prepared_stmt = await self._connection.prepare(operation)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 566, in prepare
osoc-backend_1  |     return await self._prepare(
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 584, in _prepare
osoc-backend_1  |     stmt = await self._get_statement(
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 398, in _get_statement
osoc-backend_1  |     statement = await self._protocol.prepare(
osoc-backend_1  |   File "asyncpg/protocol/protocol.pyx", line 168, in prepare
osoc-backend_1  | asyncpg.exceptions.UndefinedFunctionError: operator does not exist: integer = character varying
osoc-backend_1  | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
osoc-backend_1  | 
osoc-backend_1  | The above exception was the direct cause of the following exception:
osoc-backend_1  | 
osoc-backend_1  | Traceback (most recent call last):
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
osoc-backend_1  |     self.dialect.do_execute(
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
osoc-backend_1  |     cursor.execute(statement, parameters)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
osoc-backend_1  |     self._adapt_connection.await_(
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
osoc-backend_1  |     return current.driver.switch(awaitable)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
osoc-backend_1  |     value = await result
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
osoc-backend_1  |     self._handle_exception(error)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
osoc-backend_1  |     self._adapt_connection._handle_exception(error)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
osoc-backend_1  |     raise translated_error from error
osoc-backend_1  | sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.ProgrammingError: <class 'asyncpg.exceptions.UndefinedFunctionError'>: operator does not exist: integer = character varying
osoc-backend_1  | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
osoc-backend_1  | 
osoc-backend_1  | The above exception was the direct cause of the following exception:
osoc-backend_1  | 
osoc-backend_1  | Traceback (most recent call last):
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
osoc-backend_1  |     result = await app(self.scope, self.receive, self.send)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
osoc-backend_1  |     return await self.app(scope, receive, send)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
osoc-backend_1  |     await super().__call__(scope, receive, send)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
osoc-backend_1  |     await self.middleware_stack(scope, receive, send)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
osoc-backend_1  |     raise exc
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
osoc-backend_1  |     await self.app(scope, receive, _send)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
osoc-backend_1  |     await self.simple_response(scope, receive, send, request_headers=headers)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
osoc-backend_1  |     await self.app(scope, receive, send)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
osoc-backend_1  |     raise exc
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
osoc-backend_1  |     await self.app(scope, receive, sender)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
osoc-backend_1  |     raise e
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
osoc-backend_1  |     await self.app(scope, receive, send)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
osoc-backend_1  |     await route.handle(scope, receive, send)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
osoc-backend_1  |     await self.app(scope, receive, send)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
osoc-backend_1  |     response = await func(request)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
osoc-backend_1  |     raw_response = await run_endpoint_function(
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
osoc-backend_1  |     return await dependant.call(**values)
osoc-backend_1  |   File "/app/./app/routers/participations.py", line 81, in delete_participation
osoc-backend_1  |     student = await read_where(Student, Student.id == student_id, session=session)
osoc-backend_1  |   File "/app/./app/crud.py", line 49, in read_where
osoc-backend_1  |     res = await session.execute(statement)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 212, in execute
osoc-backend_1  |     result = await greenlet_spawn(
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 134, in greenlet_spawn
osoc-backend_1  |     result = context.throw(*sys.exc_info())
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1692, in execute
osoc-backend_1  |     result = conn._execute_20(statement, params or {}, execution_options)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
osoc-backend_1  |     return meth(self, args_10style, kwargs_10style, execution_options)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
osoc-backend_1  |     return connection._execute_clauseelement(
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
osoc-backend_1  |     ret = self._execute_context(
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
osoc-backend_1  |     self._handle_dbapi_exception(
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
osoc-backend_1  |     util.raise_(
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
osoc-backend_1  |     raise exception
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
osoc-backend_1  |     self.dialect.do_execute(
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
osoc-backend_1  |     cursor.execute(statement, parameters)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
osoc-backend_1  |     self._adapt_connection.await_(
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
osoc-backend_1  |     return current.driver.switch(awaitable)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
osoc-backend_1  |     value = await result
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
osoc-backend_1  |     self._handle_exception(error)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
osoc-backend_1  |     self._adapt_connection._handle_exception(error)
osoc-backend_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
osoc-backend_1  |     raise translated_error from error
osoc-backend_1  | sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedFunctionError'>: operator does not exist: integer = character varying
osoc-backend_1  | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
osoc-backend_1  | [SQL: SELECT student.id, student.edition_year, student.decision, student.email_sent 
osoc-backend_1  | FROM student 
osoc-backend_1  | WHERE student.id = %s]
osoc-backend_1  | [parameters: ('10',)]
osoc-backend_1  | (Background on this error at: https://sqlalche.me/e/14/f405)
```
When attempting to delete a participation this error occurs.

**Comment by Vital7788** [comment]
The email_sent attribute was added to Student, which makes the old data invalid. You should delete the data folder and repopulate the database to fix this issue.

**Comment by Vital7788** [comment]
The participation delete endpoint seems to work just fine on my computer. Could you describe the issue in more detail?

**Comment by StefVdHaute** [comment]
Continued in #407
